### ISSUE TITLE
interstitial video for going from match end --> back to commentators

### ISSUE THREAD

**Issue by cdanis** [cdanis/urzas-overlay#102]
This would be a quick (under 5 seconds) video that we'd use to give the commentators a chance to sit up and get ready to give the match postmortem commentary.  Should be silent, as they'll probably be talking the whole time.

Greg accidentally started playing the intro video this week but as it turns out it seems like just a good idea.  Cutting right to the commentators has always been kind of abrupt and hard to time correctly.  So seems like a good idea to do for real.

**Comment by terrycunha** [comment]
https://www.youtube.com/watch?v=0RadigqfIx0&feature=youtu.be



[interstitial video.mov.zip](https://github.com/cdanis/urzas-overlay/files/848749/interstitial.video.mov.zip)
