### ISSUE TITLE
New layout for sideboards

### ISSUE THREAD

**Issue by terrycunha** [cdanis/urzas-overlay#124]
![img_20170324_121714](https://cloud.githubusercontent.com/assets/6564403/24303343/02cc7c5c-108c-11e7-94f3-3f25f02f96db.jpg)

**Comment by kprevas** [comment]
The featured card view would obscure this though?

**Comment by terrycunha** [comment]
What? No. This would only appear between games and yeah, it'd make it so the featured card and cards-in-hand (CIH from now on) display wouldn't appear, but it's fine since it's only for a brief moment while the commentators talk about the sideboard.

**Comment by kprevas** [comment]
The reason we moved it up was so that Ned and Mitch could feature cards during sideboarding - see #97

**Comment by terrycunha** [comment]
Do this instead.

![img_20170324_135504](https://cloud.githubusercontent.com/assets/6564403/24307228/ae162d26-1099-11e7-8fee-a3fd1c765dba.jpg)

**Comment by cdanis** [comment]
So we'd have a different featured card view for during the game than we'd have during sideboarding??

We don't want to put the featured card in the middle of the battlefield during a game.

It's also nice to be able to show two different featured cards at once for talking about how they match up against each other.

**Comment by terrycunha** [comment]
Yes. Sideboarding is a special time and it's better to optimize the overlay graphics for that moment rather than have it be consistent with the rest of the time.

We **wouldn't** be putting it up _during_ the game, but rather in between games (aka sideboarding time).

The sideboards always get displayed between games, but cards aren't always featured in that time when they're talking about SB strategies. And when they do, my proposal would only block the red zone while the current method blocks the whole top of the battlefield.

While it may be nice to show two cards for comparison, we rarely do that during SB time since commentators take on one player's SB strategy at a time. If we really want to be able to do that, then we can just show two cards actually side-by-side in the middle, blocking everything for a brief moment.

Other streams/coverage even cut away from the battlefield, since you can't see or focus on it during SB talk anyway.

Look at this screenshot, all we get here is a nice view of the players shuffling:

<img width="930" alt="sb time" src="https://cloud.githubusercontent.com/assets/6564403/24307590/2beee61a-109b-11e7-8a6a-34dea5749094.png">
