### ISSUE TITLE
alternate side featured cards view

### ISSUE THREAD

**Issue by kprevas** [cdanis/urzas-overlay#22]
Add a mode for featured card on the right side.

**Comment by cdanis** [comment]
this should just be a checkbox to toggle a featured card on either side
a separately-settable featured card
so we could be showing Blood Moon on the loser's side, and Seal of Primordium on the clear winner's side
simultaneously

**Comment by cdanis** [comment]
hard to imagine doing this work without fixing #26 too so I'm closing that one
