### ISSUE TITLE
make some sort of index.html

### ISSUE THREAD

**Issue by cdanis** [cdanis/urzas-overlay#42]
with introductory copy and a stream schedule and stuff like that

a tournament bracket once that's a thing

**Comment by terrycunha** [comment]
To clarify, design a public home page for the website with content, some of which is a intro blurb, schedule, and bracket?

**Comment by cdanis** [comment]
yep!

**Comment by cdanis** [comment]
Intro blurb
Links to social media, YT, Twitch, etc
Decklists for each deck
Schedule -- link to the YT archive video for previous matches, have dates and decklists for future matches
Bracket


Attributions for stuff

**Comment by cdanis** [comment]
ALSO INCLUDE: a countdown timer to the NEXT LIVE STREAM

**Comment by terrycunha** [comment]
Cool, that way we can just stream the homepage with the countdown right before we go live.

**Comment by kprevas** [comment]
countdown timer has its own page now.
