### ISSUE TITLE
Card preview pane improvement

### ISSUE THREAD

**Issue by terrycunha** [cdanis/urzas-overlay#65]
The text below the card seems redundant, either remove it so the pane only show the card image, or add some insightful blurb about the card.

The background should be a subtle texture instead of a flat color, example below but not final until logo/playmat designs are ready.

<img width="992" alt="card preview" src="https://cloud.githubusercontent.com/assets/6564403/22837615/5f463004-ef8f-11e6-9360-746b8a3120a7.png">

**Comment by kprevas** [comment]
I think it looks weird with no text.  I modeled the existing text after what Wizards does on their coverage but I'm open to suggestions.

**Comment by vslashg** [comment]
For what it's worth, I liked the old text.

**Comment by cdanis** [comment]
I think including the name and type line is irrelevant but I actually like
including the set and rarity.  Maybe include the year of set release next
to the set name if that's easy -- makes it fun and gives the commentators
something to talk/reminisce about.

**Comment by kprevas** [comment]
@terrycunha do you have a texture ready for this?

**Comment by terrycunha** [comment]
I do not, but this site has good ones. Suggestion:
https://www.toptal.com/designers/subtlepatterns/dark-sharp-edges/
