### ISSUE TITLE
Add ability to display infinity as life total

### ISSUE THREAD

**Issue by vslashg** [cdanis/urzas-overlay#67]
It won't matter until it does, but infinite life gain is a thing in Modern.  It would be nice if we could set a life total to ∞.

**Comment by cdanis** [comment]
you should know better. infinite is not a thing in Magic.

a very high life total should be represented as follows:
"like a billion"

**Comment by vslashg** [comment]
Infinity isn't a thing in Magic, but aggressive pedantry is.
