### ISSUE TITLE
Create per-stream URLs for decks

### ISSUE THREAD

**Issue by 7sempra** [cdanis/urzas-overlay#94]
This would allow youtube watchers to view the the decklists.

For example: "to see today's decklists visit urzaslunchbreak.com/match/8cd4"

Prerequisites:
- Long-term server-side data storage (to store decks)
- A decklist page that supports extended card info (i.e. hover-for-card-details)

**Comment by cdanis** [comment]
this is a dup of #89 

and I don't think we need anything server-side, this can just be static content?
